openapi: '3.0.2'
info:
  title: Authentication Microservice
  version: '0.0.1'
servers:
  - url: https://authentication.reserva.emilharvey.ca
paths:
  /authentication/login:
    post:
      responses:
        '201':
          description: Authentication Passed
          content:
            application/json:
              schema:
                properties:
                  authorization:
                    $ref: "#/components/schemas/Authorization"
        '401':
          description: Authentication Failed
      requestBody:
        content:
          application/json:
            schema:
              properties:
                usernamePasswordPair:
                  $ref: "#/components/schemas/UsernamePasswordPair"
  /authentication/validate:
    put:
      responses:
        '200':
          description: Authentication Token is valid
        '401':
          description: Authentication Failed
      requestBody:
        content:
          application/json:
            schema:
              properties:
                authorization:
                  $ref: "#/components/schemas/Authorization"
  /authentication/logout:
    post:
      responses:
        '200':
          description: Logout Successful
        '401':
          description: Authentication Failed
      requestBody:
        content:
          application/json:
            schema:
              properties:
                authorization:
                  $ref: "#/components/schemas/Authorization"
  /authentication/refresh:
    post:
      responses:
        '200':
          description: Refresh Successful
        '401':
          description: Authentication Failed
      requestBody:
        content:
          application/json:
            schema:
              properties:
                authorization:
                  $ref: "#/components/schemas/Authorization"
components:
  schemas:
    $ref: "../schemas/authentication/_index.yaml"