openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.reserva.emilharvey.ca
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
components:
  schemas:
    $ref: "../schemas/_index.yaml"