openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.reserva.emilharvey.ca
paths:
  /groups/{id}:
    parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/GroupId"
    get:
      summary: Gets a Group object by id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  "Group":
                    $ref: "#/components/schemas/Group"
    put:
      summary: Updates a Group object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateGroup"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  Group:
                    $ref: "#/components/schemas/Group"
    delete:
      summary: Deletes a Group object
      responses:
        '204':
          description: Deleted
  
  /groups:
    post:  
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewGroup"

      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  Group:
                    $ref: "#/components/schemas/Group"

    get:
      summary: Gets a list of Group objects
      parameters: []
        # TODO: Add pagination parameters
        # TOOO: Add filter parameters
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  Groups:
                    type: array
                    items:
                      $ref: "#/components/schemas/Group"
            
components:
  schemas:
    $ref: "../schemas/group/_index.yaml"