openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.reserva.emilharvey.ca
paths:
  /groups/{id}:
    get:
      tags: 
        - Group Management
      summary: Gets a Group object by id
      description: >
        ## More Information

        Request for `GET /groups/{id}` requires an id which will be in the search parameter.
        Response will be in JSON format.
      operationId: getGroupId
      parameters:
        - name: id
          in: path
          description: Group ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  "Group":
                    $ref: "#/components/schemas/Group"
    put:
      tags: 
        - Group Management
      summary: Updates a Group object
      description: >
        ## More Information

        Request for `PUT /groups/{id}` requires a body that contains all information of the Group except for its id. 
        (The id of the room will be auto-incremented).
        Response body shows the body that contains 
      operationId: putRoomId
      parameters:
        - name: id
          in: path
          description: Group ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  "Group":
                    $ref: "#/components/schemas/Group"
    delete:
      tags: 
        - Group Management
      summary: Delete a Group object existing in the Groups resources
      description: >
        ## More Information

        Request for `DELETE/groups/{id}` requires an id
      operationId: deleteGroupId
      parameters:
        - name: id
          in: path
          description: Group ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted
  

  /groups:
    post: 
      tags: 
        - Group Management
      summary: Posts a Group object to the Groups resources
      description: >
        ## More Information

        Request Body: Creating Request has no parameter and has a body that contains all information on Group except for id. 
        Response Body: Response has the json body contain all parameters including id, which has been autogenerated. 
      operationId: postGroupId
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"

      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  "Group":
                    $ref: "#/components/schemas/Group"

    get:
      tags: 
        - Group Search
      summary: Gets a Group object via Search
      description: >
        ## Information

        Querying the database for Groups that fit criteria via the query parameters.

      operationId: getGroups
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    "Group":
                      $ref: "#/components/schemas/Group"
        '404':
          description: >
            Page Not Found
            
components:
  schemas:
    $ref: "../schemas/_index.yaml"