openapi: '3.0.3'
info:
  title: api title
  version: 0.0.1
servers:
  - url: https://reserva.emilharvey.ca
paths:
  /items/{id}/unavailabilities:
    parameters:
      - name: id
        in: path
        schema:
          $ref: "#/components/schemas/itemId"
        required: true
    get:
      summary: gets a list of unavailabilities for a given item.
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                properties:
                  "unavailabilities":
                    type: array
                    items:
                      $ref: "#/components/schemas/unavailability"
        '404':
          description: >
            item not found

  /items/{id}:
    parameters:
      - name: id
        in: path
        schema:
          $ref: "#/components/schemas/itemId"
        required: true
    put:
      summary: updates an item. for now, the only kind of item is a room.
      security:
        - staff: [write:items:me]
        - admin: [write:items]      
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/item"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                properties:
                  "room": # update this when we have more than one type of item
                    $ref: "#/components/schemas/item"
        '404':
          description: >
            item not found
    delete:
      summary: delete a room object
      security:
        - staff: [write:items:me]
        - admin: [write:items]
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: deleted
        '404':
          description: >
            item not found
  

  /items:
    post: 
      summary: posts an item. for now, the only kind of item is a room.
      security:
        - staff: [write:items:me]
        - admin: [write:items]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/newItem"

      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                properties:
                  "room":
                    $ref: "#/components/schemas/item"
        '400':
          description: bad request

    get:
      summary: gets a list of items. for now, the only kind of item is a room.
      # todo: add pagination
      # todo: add filtering
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                properties:
                    "rooms":
                      type: array
                      items:
                        $ref: "#/components/schemas/item"
            
components:
  schemas:
    $ref: "../schemas/item/_index.yaml"
  securitySchemes:
    $ref: '../security/_all.yaml'