openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.reserva.emilharvey.ca
paths:
  /rooms/{id}:
    get:
      tags: 
        - Room Management
      summary: Gets a Room object by id
      description: >
        ## More Information

        Request for `GET /rooms/{id}` requires an id which will be in the search parameter.
        Response will be in JSON format with S
      operationId: getRoomId
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  "Room":
                    $ref: "#/components/schemas/Room"
    put:
      tags: 
        - Room Management
      summary: Updates a Room object
      description: >
        ## More Information

        Request for `PUT /rooms/{id}` requires a body that contains all information of the Room except for its id. 
        (The id of the room will be auto-incremented).
        Response body shows the body that contains 
      operationId: putRoomId
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Room"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  "Room":
                    $ref: "#/components/schemas/Room"
    delete:
      tags: 
        - Room Management
      summary: Delete a Room object existing in the Rooms resources
      description: >
        ## More Information

        Request for `DELETE/rooms/{id}` requires an id
      operationId: deleteRoomId
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted
  

  /rooms:
    post: 
      tags: 
        - Room Management
      summary: Posts a Room object to the Rooms resources
      description: >
        ## More Information

        Request Body: Creating Request has no parameter and has a body that contains all information on Room except for id. 
        Response Body: Response has the json body contain all parameters including id, which has been autogenerated. 
      operationId: postRoomId
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Room"

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  "Room":
                    $ref: "#/components/schemas/Room"

    get:
      tags: 
        - Room Search
      summary: Gets a Room object via Search
      description: >
        ## Information

        Querying the database for Rooms that fit criteria via the query parameters.

      operationId: getRooms
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    "Room":
                      $ref: "#/components/schemas/Room"
        '404':
          description: >
            Page Not Found
            
components:
  schemas:
    $ref: "../schemas/_index.yaml"