openapi: '3.0.3'
info:
  title: api title
  version: '0.0.1'
servers:
  - url: https://reserva.emilharvey.ca
  - url: http://localhost:8080
paths:
  /unavailabilities/{id}:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/unavailabilityId"
      description: the unavailability id
    put:
      summary: update an unavailability
      security:
        - staff: [write:unavailabilities:me]
        - standard: [write:unavailabilities:me]
      
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking:
                    type: object
                    $ref: "#/components/schemas/updateUnavailability"
          description: ok
        '400':
          content:
            application/json:
              schema:
                $ref: '../schemas/meta/error.yaml'
          description: bad request
    delete:
      summary: Delete an unavailability
      security:
        - staff: [write:unavailabilities:me]
        - standard: [write:unavailabilities:me]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "../schemas/meta/success.yaml"
          description: deleted
        '400':
          content:
            application/json:
              schema:
                $ref: '../schemas/meta/error.yaml'
          description: bad request
          
  /unavailabilities:   
    post:
      summary: Create a new unavailability
      security:
        - staff: [write:unavailabilities:me]
        - standard: [write:unavailabilities:me]
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/newUnavailability"
                - $ref: "#/components/schemas/newRecurringUnavailability"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  unavailability:
                    type: object
                    $ref: "#/components/schemas/unavailability"
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '../schemas/meta/error.yaml'
          description: bad request


components:
  schemas:
    $ref: "../schemas/unavailability/_index.yaml"
  securitySchemes:
    $ref: '../security/_all.yaml'