openapi: 3.0.3
info:
  title: user service api
  description: this api manages user authentication, authorization, and admin management.
  version: 0.0.1
servers:
  - url: http://reserva.emilharvey.ca
paths:
  /users:
    get:
      summary: get all users
      description: returns a list of all users.
      responses:
        "200":
          description: a list of users
          content:
            application/json:
              schema:
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/user"
  /users/{userId}:
    get:
      summary: get a user by id
      description: returns a single user by id.
      parameters:
        - name: userId
          in: path
          required: true
          description: the id of the user to retrieve.
          schema:
            type: integer
      responses:
        "200":
          description: the requested user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "404":
          description: user not found
  /users/admins:
    get:
      summary: get all admin users
      description: returns a list of all admin users.
      responses:
        "200":
          description: a list of admin users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
  /users/standard:
    get:
      summary: get all standard users
      description: returns a list of all standard users.
      responses:
        "200":
          description: a list of standard users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
  /users/{userId}/groups:
    get:
      summary: get all groups for a user
      description: returns a list of all groups for a user.
      parameters:
        - name: userId
          in: path
          required: true
          description: the id of the user to retrieve groups for.
          schema:
            type: integer
      responses:
        "200":
          description: a list of groups
          content:
            application/json:
              schema:
                properties:  
                  groups:
                    type: array
                    items:
                      $ref: "#/components/schemas/groupMembership"
        
components:
  schemas:
    $ref: "../schemas/user/_index.yaml"
  securitySchemes:
    $ref: '../security/_all.yaml'