openapi: 3.0.3
info:
  title: user service api
  description: this api manages user authentication, authorization, and admin management.
  version: 0.0.1
servers:
  - url: http://reserva.emilharvey.ca
  - url: http://localhost:8080
paths:
  /users:
    get:
      security:
        - admin: []
        - staff: []
        - standard: []      
      summary: get all users
      description: returns a list of all users.
      parameters:
        - name: search
          in: query
          required: false
          description: a search string to filter users by.
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: the page of users to retrieve.
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 1
        - name: per_page
          in: query
          required: false
          description: the number of users to retrieve per page.
          schema:
            type: integer
            format: int64
            maximum: 100
            default: 10
            minimum: 1
      responses:
        "200":
          description: a list of users
          content:
            application/json:
              schema:
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/user"

  /users/me:
    get:
      summary: get the current user
      description: returns the current user.
      security:
        - standard: []
        - admin: []
        - staff: []
      responses:
        "200":
          description: the current user
          content:
            application/json:
              schema:
                properties:
                  user:
                    $ref: "#/components/schemas/user"

  /users/me/unavailabilities:
    get:
      summary: get all unavailabilities for the current user
      description: returns a list of all unavailabilities for the current user.
      security:
        - standard: []
        - admin: []
        - staff: []
      parameters:
        - name: start
          in: query
          required: false
          description: the start of the time range to retrieve unavailabilities for.
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          required: false
          description: the end of the time range to retrieve unavailabilities for.
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: a list of unavailabilities
          content:
            application/json:
              schema:
                properties:  
                  unavailabilities:
                    type: array
                    items:
                      $ref: "#/components/schemas/unavailability"
  /users/me/groups:
    get:
      summary: get all groups for the current user
      description: returns a list of all groups for the current user.
      security:
        - standard: []
        - admin: []
        - staff: []
      responses:
        "200":
          description: a list of groups
          content:
            application/json:
              schema:
                properties:  
                  groups:
                    type: array
                    items:
                      $ref: "#/components/schemas/groupMembership"
        
components:
  schemas:
    $ref: "../schemas/user/_index.yaml"
  securitySchemes:
    $ref: '../security/_all.yaml'