---
version: '3'
services:
  # Database
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  # # Backend
  # backend:
  #   build: ./backend
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     MONGO_URL: mongodb://root:example@mongo:27017/
  #     MONGO_DB: example 
  #   depends_on:
  #     - mongo
  
  # # Frontend
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   environment:
  #     REACT_APP_BACKEND_URL: http://localhost:8080
  #   depends_on:
  #     - backend