name: Build API Webpage
on:
    push:
        branches:
            - main
        paths:
            - 'api/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10' 
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r api/requirements.txt
            - name: Generate OpenAPI singleton
              run: |
                python api/schemas/create_all_schemas.py
                api/service_routes/create_all_routes.py
            - name: Generate Swagger UI
              uses: Legion2/swagger-ui-action@v1
              with:
                output: api/swagger-ui
                spec-file: api/service_routes/_all.yaml
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: swagger-ui