name: Build Frontend
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'microservices/webapp/vite-react/**'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: microservices/webapp/vite-react/package.json
    - run: npm install
      working-directory: microservices/webapp/vite-react
    - run: npm run build --if-present
      working-directory: microservices/webapp/vite-react
    - run: npm test
      working-directory: microservices/webapp/vite-react
