name: Validate OpenAPI YAML

on:
  pull_request:
    paths:
    - 'api/**/*.yaml'

jobs:
  validate:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v2
          
          - uses: actions/setup-node@v3
            with:
              node-version: 18
          
          - name: Install Swagger CLI
            run: npm install -g swagger-cli
    
          - name: Validate Swagger and OpenAPI using Swagger CLI
            run: |
              swagger-cli validate api/service_routes/group.yaml        
              swagger-cli validate api/service_routes/item.yaml
              swagger-cli validate api/service_routes/unavailability.yaml
              swagger-cli validate api/service_routes/user.yaml